version: '3'

services:
  myapp: 
    build: .
    ports:
     - "5000:5000"
  mysql:
    image: "mysql"
    ports:
     - "8000:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: password
    volumes:
     - db_data:/var/lib/mysql
  postgres: 
    image: "postgres"
    ports: 
     - "8001:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:  
     - db-data1:/var/lib/postgresql/data
  mongodb: 
    image: "mongo"
    ports: 
     - "8002:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes: 
      - mongodata:/data/db

volumes: 
  db_data: 
  db-data1:
  mongodata:  
